### PR TITLE
Next version

### PR DESCRIPTION
**Pull request by Kcchouette**
- Priorizing all protocols
 - Adding Encoding to hublist web

### CODE REVIEW

**Comment by Kcchouette** [comment]
> This is wrong URL. Look into `eiskaltdcpp-qt` code because Qt UI is much widely used (this is the only one UI available in macOS, Windows, Haiku).

Is it the link: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/HubEntry.h#L43 ?

**Comment by tehnick** [comment]
> Is it the link: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/HubEntry.h#L43 ?

Of course not.

**Comment by tehnick** [comment]
> > Is it the link: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/HubEntry.h#L43 ?
> 
> Of course not.

But probably this was too strong assertion...
Could you describe what **exactly** do you need?

**Comment by Kcchouette** [comment]
> > > Is it the link: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/HubEntry.h#L43 ?
> > 
> > 
> > Of course not.
> 
> But probably this was too strong assertion...
> Could you describe what **exactly** do you need?

The parsing that eiskaltDC++ does from XML.BZ2 public hublist, where we can exactly see which attributes of the XML is used

**Comment by tehnick** [comment]
> from XML.BZ2 public hublist, where we can exactly see which attributes of the XML is used

Probably this is what you are looking for:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/FavoriteManager.cpp#L255

**Comment by Kcchouette** [comment]
> > from XML.BZ2 public hublist, where we can exactly see which attributes of the XML is used
> 
> Probably this is what you are looking for:
> https://github.com/eiskaltdcpp/eiskaltdcpp/blob/2b38b58eed1547f1a6769d8c7c3a7039dda54c39/dcpp/FavoriteManager.cpp#L255

Indeed :/

**Pull request merged**
